#ifndef LEPUS_GFX_MATERIAL_ATTRIBUTES
#define LEPUS_GFX_MATERIAL_ATTRIBUTES
#include "lepus/gfx/GraphicsEngine/GraphicsApi/Uniforms.h"
#include "lepus/utility/types/List.h"

#include <cassert>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <stdexcept>

#define MAT_ATTRIBUTE(type, name) lepus::utility::List<type> name{lepus::utility::List<type>()};

namespace lepus
{
    namespace gfx
    {
	typedef uint8_t MaterialAttributeHandle;

	class MaterialAttributes
	{
	    private:
	    uint8_t m_AttribCount{0};
	    utility::List<const char*> m_AttribNames{utility::List<const char*>()};
	    utility::List<UniformType> m_AttribTypes{utility::List<UniformType>()};

	    utility::List<uint8_t> m_AttribIndex{utility::List<uint8_t>()};

	    struct AttributeData
	    {
		MAT_ATTRIBUTE(float[4 * 4], mat4)
		MAT_ATTRIBUTE(float, scalar)
		MAT_ATTRIBUTE(float[2], vec2)
		MAT_ATTRIBUTE(float[3], vec3)
		MAT_ATTRIBUTE(float[4], vec4)
	    } m_AttribData;

	    protected:
	    template <typename TValue>
	    inline void UnsafeSet(MaterialAttributeHandle handle, TValue value)
	    {
		assert(handle < m_AttribCount);

		auto index = m_AttribIndex.Get(handle);

		utility::List<TValue>& list = getDataList(m_AttribTypes.Get(index));
		memcpy(list.Raw()[index], &value, sizeof(TValue));
	    }

	    template <typename TValue>
	    inline utility::List<TValue>& getDataList(UniformType type)
	    {
		// Could probably have a function template for getting these and have the template instantiations generated by the MAT_ATTRIBUTE macro but this works for now
		switch (type)
		{
		case VEC3:
		    return (utility::List<TValue>&)(m_AttribData.vec3);
		case MATRIX4:
		    return (utility::List<TValue>&)(m_AttribData.mat4);
		case FLOAT:
		    return (utility::List<TValue>&)(m_AttribData.scalar);
		case INVALID:
		default:
		    assert(false);
		}

		throw std::invalid_argument("getDataList: invalid uniform type");
	    }

	    template <typename TValue>
	    UniformType getDataType();

	    public:
	    MaterialAttributes() = default;

	    /// @brief Adds an attribute and returns its index.
	    template <typename TValue = const void*>
	    MaterialAttributeHandle Add(const char* name, TValue value)
	    {
		UniformType dataType = getDataType<TValue>();
		utility::List<TValue>& targetDataList = getDataList<TValue>(dataType);

		size_t numChars = strlen(name);
		const char* newName = new char[numChars + 1];
		memcpy((void*)newName, name, numChars);
		memset((void*)(newName + numChars), 0, sizeof(char));
		m_AttribNames.Push(newName);

		auto newValueIndex = targetDataList.Count();
		m_AttribTypes.Push(dataType);
		Set<TValue>(newValueIndex, value);
		m_AttribIndex.Push(newValueIndex);

		return newValueIndex;
	    }

	    template <typename TValue = const void*>
	    void Set(MaterialAttributeHandle handle, TValue value)
	    {
		assert(handle < m_AttribCount);

		auto& list = getDataList(m_AttribTypes.Get(handle));
		auto index = m_AttribIndex.Get(handle);
		list.Raw()[index] = value;
	    }

	    template <typename TValue = void*>
	    inline TValue Get(MaterialAttributeHandle handle)
	    {
		assert(handle < m_AttribCount);

		utility::List<TValue>& list = getDataList<TValue>(m_AttribTypes.Get(handle));
		auto index = m_AttribIndex.Get(handle);
		return (TValue)(list.Get(index));
	    }

	    [[nodiscard]] inline const char* GetName(MaterialAttributeHandle handle) const
	    {
		assert(handle < m_AttribCount);

		return m_AttribNames.Get(handle);
	    }

	    [[nodiscard]] inline uint8_t Count() const
	    {
		return m_AttribCount;
	    }

	    [[nodiscard]] inline UniformType GetType(MaterialAttributeHandle handle) const
	    {
		return m_AttribTypes.Get(handle);
	    }

	    ~MaterialAttributes()
	    {
		for (uint8_t i = 0; i < m_AttribCount; i++)
		{
		    delete[] m_AttribNames.Get(i);
		}
	    }
	};

	template <>
	inline constexpr UniformType MaterialAttributes::getDataType<float>()
	{
	    return FLOAT;
	}

	template <>
	inline constexpr UniformType MaterialAttributes::getDataType<float[3]>()
	{
	    return VEC3;
	}

	template <>
	inline constexpr UniformType MaterialAttributes::getDataType<float[4 * 4]>()
	{
	    return MATRIX4;
	}

	template <>
	inline constexpr UniformType MaterialAttributes::getDataType<const math::Matrix4x4&>()
	{
	    return MATRIX4;
	}

	template <>
	inline void MaterialAttributes::Set<float>(MaterialAttributeHandle handle, float value)
	{
	    auto index = m_AttribIndex.Get(handle);
	    m_AttribTypes.Set(handle, UniformType::FLOAT);
	    m_AttribData.scalar.Set(index, value);
	}

	template <>
	inline void MaterialAttributes::Set<const lepus::math::Matrix4x4&>(MaterialAttributeHandle handle, const lepus::math::Matrix4x4& value)
	{
	    auto index = m_AttribIndex.Get(handle);

	    m_AttribTypes.Set(handle, UniformType::MATRIX4);
	    memcpy(m_AttribData.mat4.Raw()[index], value.data(), sizeof(float) * 4 * 4);
	}

	template <>
	inline void MaterialAttributes::Set<const lepus::types::Vector3&>(MaterialAttributeHandle handle, const lepus::types::Vector3& value)
	{
	    auto index = m_AttribIndex.Get(handle);

	    m_AttribTypes.Set(handle, UniformType::VEC3);
	    memcpy(m_AttribData.vec3.Raw()[index], value.GetData(), sizeof(float) * 3);
	}

	template <>
	inline float MaterialAttributes::Get<float>(MaterialAttributeHandle handle)
	{
	    auto index = m_AttribIndex.Get(handle);
	    return m_AttribData.scalar.Get(index);
	}

	template <>
	inline lepus::math::Matrix4x4 MaterialAttributes::Get<lepus::math::Matrix4x4>(MaterialAttributeHandle handle)
	{
	    auto index = m_AttribIndex.Get(handle);
	    lepus::math::Matrix4x4 mat(m_AttribData.mat4.Get(index));

	    return mat;
	}

	// template <>
	// inline void MaterialAttributes::Set<const float* const>(uint8_t index, const float* const value)
	// {
	//     memcpy(m_AttribValues[index], value, sizeof(value));
	// }
    } // namespace gfx
} // namespace lepus

#undef MAT_ATTRIBUTE

#endif
