#ifndef LEPUS_GFX_MATERIAL_ATTRIBUTES
#define LEPUS_GFX_MATERIAL_ATTRIBUTES
#include "AttributeTypes.h"
#include "lepus/gfx/GraphicsEngine/GraphicsApi/Uniforms.h"
#include "lepus/utility/types/List.h"
#include "lepus/utility/types/Matrix4x4.h"
#include "lepus/utility/types/Vector.h"

#include <cassert>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <cstddef>
#include <stdexcept>

#define MAT_ATTRIBUTE(type, name) lepus::utility::List<type> name{lepus::utility::List<type>()};

namespace lepus
{
    namespace gfx
    {
	typedef uint8_t MaterialAttributeHandle;

	template <typename TValue, typename TRaw = void*>
	class MaterialAttributeView;

	class MaterialAttributes
	{
	    private:
	    friend class MaterialAttributeProxy;

	    uint8_t m_AttribCount{0};
	    utility::List<const char*> m_AttribNames{utility::List<const char*>()};
	    utility::List<UniformType> m_AttribTypes{utility::List<UniformType>()};

	    utility::List<uint8_t> m_AttribIndex{utility::List<uint8_t>()};

	    struct AttributeData
	    {
		MAT_ATTRIBUTE(float[4 * 4], mat4)
		MAT_ATTRIBUTE(float, scalar)
		MAT_ATTRIBUTE(float[2], vec2)
		MAT_ATTRIBUTE(float[3], vec3)
		MAT_ATTRIBUTE(float[4], vec4)
	    } m_AttribData;

	    protected:
	    template <typename TValue>
	    inline void UnsafeSet(MaterialAttributeHandle handle, TValue value)
	    {
		assert(handle < m_AttribCount);

		auto index = m_AttribIndex.Get(handle);

		utility::List<TValue>& list = getDataList(m_AttribTypes.Get<TValue>(index));
		memcpy(list.Raw()[index], &value, sizeof(TValue));
	    }

	    template <typename TValue>
	    inline utility::List<TValue>& getDataList(UniformType type) const
	    {
		// Could probably have a function template for getting these and have the template instantiations generated by the MAT_ATTRIBUTE macro but this works for now
		switch (type)
		{
		case VEC3:
		    return (utility::List<TValue>&)(m_AttribData.vec3);
		case MATRIX4:
		    return (utility::List<TValue>&)(m_AttribData.mat4);
		case FLOAT:
		    return (utility::List<TValue>&)(m_AttribData.scalar);
		case INVALID:
		default:
		    assert(false);
		}

		throw std::invalid_argument("getDataList: invalid uniform type");
	    }

	    template <typename TValue>
	    static UniformType getDataType();

	    public:
	    MaterialAttributes() = default;

	    /// @brief Adds an attribute and returns its index.
	    template <typename TValue, typename TRaw = void*>
	    MaterialAttributeView<TValue, TRaw> Add(const char* name, TValue value);

	    template <typename TValue = const void*>
	    void Set(MaterialAttributeHandle handle, TValue value)
	    {
		assert(handle < m_AttribCount);

		auto dataType = getDataType<TValue>();
		auto& list = getDataList<TValue>(m_AttribTypes.Get(handle));
		auto index = m_AttribIndex.Get(handle);
		// list.Raw()[index] = value;
		size_t valueSize = AttributeTypes::GetDataSize(dataType);
		memcpy(list.Raw() + index, value, valueSize);
	    }

	    template <typename TValue = void*>
	    inline TValue Get(MaterialAttributeHandle handle)
	    {
		assert(handle < m_AttribCount);

		utility::List<TValue>& list = getDataList<TValue>(m_AttribTypes.Get(handle));
		auto index = m_AttribIndex.Get(handle);
		return (TValue)(list.Get(index));
	    }

	    inline void* GetRaw(MaterialAttributeHandle handle)
	    {
		assert(handle < m_AttribCount);

		utility::List<void*>& list = getDataList<void*>(m_AttribTypes.Get(handle));
		auto index = m_AttribIndex.Get(handle);
		return list.Raw() + index * AttributeTypes::GetDataSize(m_AttribTypes.Get(handle));
	    }

	    [[nodiscard]] inline const char* GetName(MaterialAttributeHandle handle) const
	    {
		assert(handle < m_AttribCount);

		return m_AttribNames.Get(handle);
	    }

	    [[nodiscard]] inline uint8_t Count() const
	    {
		return m_AttribCount;
	    }

	    [[nodiscard]] inline UniformType GetType(MaterialAttributeHandle handle) const
	    {
		return m_AttribTypes.Get(handle);
	    }

	    ~MaterialAttributes()
	    {
		for (uint8_t i = 0; i < m_AttribCount; i++)
		{
		    delete[] m_AttribNames.Get(i);
		}
	    }
	};

	template <>
	inline constexpr UniformType MaterialAttributes::getDataType<float>()
	{
	    return FLOAT;
	}

	template <>
	inline constexpr UniformType MaterialAttributes::getDataType<float[3]>()
	{
	    return VEC3;
	}

	template <>
	inline constexpr UniformType MaterialAttributes::getDataType<float[4 * 4]>()
	{
	    return MATRIX4;
	}

	template <>
	inline constexpr UniformType MaterialAttributes::getDataType<const math::Matrix4x4&>()
	{
	    return MATRIX4;
	}

	template <>
	inline void MaterialAttributes::Set<float>(MaterialAttributeHandle handle, float value)
	{
	    auto index = m_AttribIndex.Get(handle);
	    m_AttribTypes.Set(handle, UniformType::FLOAT);
	    m_AttribData.scalar.Set(index, value);
	}

	template <>
	inline void MaterialAttributes::Set<const lepus::math::Matrix4x4&>(MaterialAttributeHandle handle, const lepus::math::Matrix4x4& value)
	{
	    auto index = m_AttribIndex.Get(handle);

	    m_AttribTypes.Set(handle, UniformType::MATRIX4);
	    memcpy(m_AttribData.mat4.Raw()[index], value.data(), sizeof(float) * 4 * 4);
	}

	template <>
	inline void MaterialAttributes::Set<const lepus::types::Vector3&>(MaterialAttributeHandle handle, const lepus::types::Vector3& value)
	{
	    auto index = m_AttribIndex.Get(handle);

	    m_AttribTypes.Set(handle, UniformType::VEC3);
	    memcpy(m_AttribData.vec3.Raw()[index], value.GetData(), sizeof(float) * 3);
	}

	template <>
	inline float MaterialAttributes::Get<float>(MaterialAttributeHandle handle)
	{
	    auto index = m_AttribIndex.Get(handle);
	    return m_AttribData.scalar.Get(index);
	}

	template <>
	inline lepus::math::Matrix4x4 MaterialAttributes::Get<lepus::math::Matrix4x4>(MaterialAttributeHandle handle)
	{
	    auto index = m_AttribIndex.Get(handle);
	    lepus::math::Matrix4x4 mat(m_AttribData.mat4.Get(index));

	    return mat;
	}

	class MaterialAttributeProxy
	{
	    protected:
	    template <typename TValue>
	    static inline utility::List<TValue>& getData(const MaterialAttributes& attribs, UniformType& outType)
	    {
		return attribs.getDataList<TValue>(attribs.getDataType<TValue>());
	    }

	    static inline uint8_t getIndex(const MaterialAttributes& attribs, MaterialAttributeHandle handle)
	    {
		return attribs.m_AttribIndex.Get(handle);
	    }

	    template <typename TValue>
	    static inline UniformType getType()
	    {
		return MaterialAttributes::getDataType<TValue>();
	    }
	};

	template <typename TInput, typename TRaw>
	class MaterialAttributeView : public MaterialAttributeProxy
	{
	    private:
	    bool m_Initialised{false};
	    // utility::List<TValue>& m_Container;
	    // uint8_t m_Index{0};
	    MaterialAttributeHandle m_Handle{0};
	    UniformType m_Type{INVALID};
	    TRaw* m_Data{nullptr};

	    public:
	    static inline constexpr size_t GetDataSize(UniformType type)
	    {
		switch (type)
		{
		case FLOAT:
		    return sizeof(float);
		case VEC3:
		    return sizeof(float) * 3;
		case MATRIX4:
		    return sizeof(float) * 4 * 4;
		case INVALID:
		default:
		    return 0;
		}
	    }

	    MaterialAttributeView() = delete;

	    MaterialAttributeView(const MaterialAttributes& materialAttributes, MaterialAttributeHandle handle)
	    {
		m_Handle = handle;
		m_Data = (getData<TRaw>(materialAttributes, m_Type).Raw() + getIndex(materialAttributes, handle));
		m_Initialised = true;
	    }

	    MaterialAttributeView(utility::List<TRaw>& container, uint8_t index, MaterialAttributeHandle handle)
	    {
		m_Handle = handle;
		m_Data = (container.Raw() + index);
		m_Type = getType<TRaw>();
		m_Initialised = true;
	    }

	    MaterialAttributeView(utility::List<TRaw>& container, uint8_t index, MaterialAttributeHandle handle, UniformType type)
	    {
		m_Handle = handle;
		m_Data = (container.Raw() + index);
		m_Type = type;
	    }

	    void Set(TInput& value)
	    {
		memcpy(m_Data, value, AttributeTypes::GetDataSize(m_Type));
		// m_Data.Set(m_Index, value);
	    }

	    void Set(TRaw* value)
	    {
		memcpy(m_Data, value, sizeof(TRaw));
	    }

	    TInput Get()
	    {
		return TInput(*m_Data);
	    }
	};

	template class MaterialAttributeView<const types::Vector3, float[3]>;

#define MAT_ATTRIBUTE_VEC3 const lepus::types::Vector3, float[3]

	template <typename TValue, typename TRaw>
	lepus::gfx::MaterialAttributeView<TValue, TRaw> lepus::gfx::MaterialAttributes::Add(const char* name, TValue value)
	{
	    UniformType dataType = getDataType<TRaw>();
	    utility::List<TRaw>& targetDataList = getDataList<TRaw>(dataType);

	    size_t numChars = strlen(name);
	    const char* newName = new char[numChars + 1];
	    memcpy((void*)newName, name, numChars);
	    memset((void*)(newName + numChars), 0, sizeof(char));
	    m_AttribNames.Push(newName);

	    auto newValueIndex = targetDataList.Count();
	    ++m_AttribCount;
	    m_AttribTypes.Push(dataType);
	    m_AttribIndex.Push(newValueIndex);
	    auto& list = getDataList<TValue>(dataType);
	    list.EnsureCapacity(newValueIndex + 1);
	    Set<TRaw>(newValueIndex, value);
	    list.UnsafeSetCount(newValueIndex + 1);

	    return lepus::gfx::MaterialAttributeView<TValue, TRaw>(targetDataList, newValueIndex, m_AttribCount, dataType);
	}

	// template <>
	// inline void MaterialAttributes::Set<const float* const>(uint8_t index, const float* const value)
	// {
	//     memcpy(m_AttribValues[index], value, sizeof(value));
	// }
    } // namespace gfx
} // namespace lepus

#undef MAT_ATTRIBUTE

#endif
