name: ci
on: [push]
jobs:
    run-ci:
        runs-on: ubuntu-latest
        steps:
            - 
                name: setup-env
                run: cd ~ && ${{github.workspace}}/scripts/install-ubuntu.sh